spring:
  application:
    name: login
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

  instance:
    prefer-ip-address: true

server:
  port: 8010