server:
  port: 8090

spring:
  application:
    name: gateaway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
           '[/**]':
             allowedOrigins:
               - "http://localhost:4200"
             allowedMethods:
               - GET
               - POST
               - PUT
               - DELETE
               - OPTIONS
             allowedHeaders: "*"
             allowCredentials: true

      discovery:
        locator:
          enabled: false #nos ayuda a enrutar los servicios#          lower-case-service-id: true
      routes:
        - id: productos
          uri: lb://PRODUCTOS  # ← Mayúsculas como aparece en Eureka
          predicates:
            - Path=/api/productos/**

        - id: categorias
          uri: lb://PRODUCTOS
          predicates:
            - Path=/api/categoria/**

        - id: ventas
          uri: lb://VENTAS
          predicates:
            - Path=/api/ventas/**

        - id: clientes
          uri: lb://CLIENTES
          predicates:
            - Path=/api/clientes/**

        - id: login
          uri: lb://LOGIN
          predicates:
            - Path=/api/auth/**

        - id: rol
          uri: lb://LOGIN
          predicates:
            - Path=/api/rol/**

        - id: usuario
          uri: lb://LOGIN
          predicates:
            - Path=/api/usuario/**

        - id: consolidado
          uri: lb://CONSOLIDADO
          predicates:
            - Path=/api/consolidado/**

        - id: inventario
          uri: lb://INVENTARIO
          predicates:
            - Path=/api/inventario/**

        - id: sede
          uri: lb://INVENTARIO
          predicates:
            - Path=/api/sede/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
